APP_NAME = "local_rag_assistant"

CHAT_MODEL_ALIAS = "qwen2.5-0.5b"
EMBEDDING_MODEL_ALIAS = "qwen3-embedding-0.6b"

DOCS_DIR = "data/docs"
DATABASE_PATH = "data/rag.db"
CHUNK_MAX_WORDS = 120
CHUNK_OVERLAP_WORDS = 25
TOP_K = 3
RETRIEVAL_MIN_SCORE = 0.30
CHAT_TEMPERATURE = 0.1
CHAT_MAX_TOKENS = 90
MAX_ANSWER_CHARS = 420
